/*
 * Copyright (c) Huawei Device Co., Ltd. 2024-2025. All rights reserved.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export class AnimationConstants {
  public static readonly AOD_MASK_GEO_ENTER_DELAY: number = 0;

  public static readonly AOD_MASK_GEO_ENTER_DURATION: number = 850;

  public static readonly AOD_MASK_GEO_EXIT_DELAY: number = 0;

  public static readonly AOD_MASK_GEO_EXIT_DURATION: number = 1000;

  public static readonly AOD_MASK_OPACITY_ENTER_DELAY: number = 0;

  public static readonly AOD_MASK_OPACITY_ENTER_DURATION: number = 300;

  public static readonly AOD_MASK_OPACITY_EXIT_DELAY: number = 650;

  public static readonly AOD_MASK_OPACITY_EXIT_DURATION: number = 450;

  public static readonly WALLPAPER_GEO_ENTER_DELAY: number = 0;

  public static readonly WALLPAPER_GEO_ENTER_DURATION: number = 800;

  public static readonly WALLPAPER_GEO_EXIT_DELAY: number = 100;

  public static readonly WALLPAPER_GEO_EXIT_DURATION: number = 850;

  public static readonly AOD_INVISIBLE_SCALE: number = 3.5;
}