/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2024-2025. All rights reserved.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import { LogDomain, LogHelper } from '@ohos/basicutils';

const TAG = 'SceneMsgUtils';
const log: LogHelper = LogHelper.getLogHelper(LogDomain.HOME, TAG);

/**
 * 场景操作工具类
 */
export class SceneMsgUtils {
}

/**
 * 场景参数枚举
 */
export enum SceneMsgEnum {
  // 100001  - 109999 刷新场景
  // 桌面启动
  SCENE_MSG_DESKTOP_REFRESH = '100001|SCENE_MSG_DESKTOP_INIT',
  // 切换简易布局
  SCENE_MSG_SWITCH_TO_SIMPLE_LAYOUT = '100002|SCENE_MSG_SWITCH_TO_SIMPLE_LAYOUT',
  // 系统语言切换
  SCENE_MSG_SYSTEM_LANGUAGE_CHANGE = '100003|SCENE_MSG_SYSTEM_LANGUAGE_CHANGE',
  // 初始化dock布局结束事件
  SCENE_MSG_SMART_DOCK_INIT_FINISHED = '100004|SCENE_MSG_SMART_DOCK_INIT_FINISHED',
  // PC刷新桌面
  SCENE_MSG_PC_DESKTOP_REFRESH = '100005|SCENE_MSG_PC_DESKTOP_REFRESH',
  // PC loadPersistConfig
  SCENE_MSG_PC_LOAD_PERSIST_CONFIG = '100006|SCENE_MSG_PC_LOAD_PERSIST_CONFIG',
  // 在首次OOBE未结束前，对桌面首页布局和预制布局首页图标布局进行比对，如果存在不一致情况，进行兜底处理，重新恢复预制布局配置
  SCENE_MSG_SCB_PREVIEW_CHECK = '100007|SCENE_MSG_SCB_PREVIEW_CHECK',
  // VDE外屏loadPersistConfig
  SCENE_MSG_OUTER_LOAD_PERSIST_CONFIG = '100008|SCENE_MSG_OUTER_LOAD_PERSIST_CONFIG',
  // VDE外屏从配置文件加载
  SCENE_MSG_OUTER_LOAD_FROM_CONFIGURATION = '100009|SCENE_MSG_OUTER_LOAD_FROM_CONFIGURATION',
  // Phone loadPersistConfig
  SCENE_MSG_PHONE_LOAD_PERSIST_CONFIG = '100010|SCENE_MSG_PHONE_LOAD_PERSIST_CONFIG',
  // Phone从配置文件加载
  SCENE_MSG_PHONE_LOAD_FROM_CONFIGURATION = '100011|SCENE_MSG_PHONE_LOAD_FROM_CONFIGURATION',
  // switchSingleDisplay
  SCENE_MSG_SWITCH_SINGLE_DISPLAY = '100012|SCENE_MSG_SWITCH_SINGLE_DISPLAY',
  // uninstallAppResult 卸载APP
  SCENE_MSG_UNINSTALL_APP = '100013|SCENE_MSG_UNINSTALL_APP',
  // 克隆后刷新桌面
  SCENE_MSG_CLONE_REFRESH_DESKTOP = '100014|SCENE_MSG_CLONE_REFRESH_DESKTOP',
  // 恢复VDE外屏
  SCENE_MSG_RESTORING_VDE_OUTER = '100015|SCENE_MSG_RESTORING_VDE_OUTER',
  // 恢复VDE内屏
  SCENE_MSG_RESTORING_VDE = '100016|SCENE_MSG_RESTORING_VDE',
  // 桌面恢复
  SCENE_MSG_RESTORING_PHONE = '100017|SCENE_MSG_RESTORING_PHONE',
  // 设置项改变
  SCENE_MSG_SETTINGS_CHANGE = '100018|SCENE_MSG_SETTINGS_CHANGE',
  // 文件夹数据更新
  SCENE_MSG_UPDATE_FOLDER_DATA = '100021|SCENE_MSG_UPDATE_FOLDER_DATA',
  // 卡片ID变化
  SCENE_MSG_FORM_ITEM_RELATIVE_FORM_ID_CHANGE = '100022|SCENE_MSG_FORM_ITEM_RELATIVE_FORM_ID_CHANGE',
  // 外屏从数据库刷新
  SCENE_MSG_REFRESH_OUTER_FROM_DB = '100023|SCENE_MSG_REFRESH_OUTER_FROM_DB',
  // 从桌面删除卡片
  SCENE_MSG_DELETE_FORM_ITEM = '100024|SCENE_MSG_DELETE_FORM_ITEM',
  // 添加空白页
  SCENE_MSG_ADD_BLANK_PAGE = '100025|SCENE_MSG_ADD_BLANK_PAGE',
  // 添加应用到桌面
  SCENE_MSG_ADD_TO_DESKTOP = '100026|SCENE_MSG_ADD_TO_DESKTOP',
  // 从桌面删除元素 补位操作
  SCENE_MSG_DELETE_DESKTOP_ITEM = '100027|SCENE_MSG_DELETE_DESKTOP_ITEM',
  // 桌面数据修剪
  SCENE_MSG_DESKTOP_TRIM = '100028|SCENE_MSG_DESKTOP_TRIM',
  // 添加新的APP
  SCENE_MSG_INSERT_NEW_UPDATE_APP = '100029|SCENE_MSG_INSERT_NEW_UPDATE_APP',
  // 添加卡片到桌面
  SCENE_MSG_CREATE_CARD_TO_DESKTOP = '100030|SCENE_CREATE_CARD_TO_DESKTOP',
  // BMS比对
  SCENE_MSG_UPDATE_BMS_CHANGED_APP = '100031|SCENE_MSG_UPDATE_BMS_CHANGED_APP',
  // RGM状态改变
  SCENE_MSG_RGM_STATUS_CHANGE = '100032|SCENE_MSG_RGM_STATUS_CHANGE',
  // 堆叠卡片状态改变
  SCENE_MSG_FORM_STACK_STATUS_CHANGED = '100033|SCENE_MSG_FORM_STACK_STATUS_CHANGED',
  // 应用内快捷方式加桌
  SCENE_MSG_ADD_SHORTCUT_TO_DESKTOP = '100034|SCENE_MSG_ADD_SHORTCUT_TO_DESKTOP',
  // 应用安装或更新
  SCENE_MSG_APP_ADDED_OR_UPDATED = '100035|SCENE_MSG_APP_ADDED_OR_UPDATED',
  // 文件夹内删除菜单点击
  SCENE_MSG_REMOVE_MENU_CLICK_IN_FOLDER = '100037|SCENE_MSG_REMOVE_MENU_CLICK_IN_FOLDER',
  // 更新时解散Dock文件夹
  SCENE_MSG_UPDATE_TO_RELEASE_FOLDER_ON_DOCK = '100038|SCENE_MSG_UPDATE_TO_RELEASE_FOLDER_ON_DOCK',
  // 更新时解散桌面文件夹
  SCENE_MSG_UPDATE_TO_RELEASE_FOLDER_ON_DESKTOP = '100039|SCENE_MSG_UPDATE_TO_RELEASE_FOLDER_ON_DESKTOP',
  // 更新Dock文件夹
  SCENE_MSG_UPDATE_FOLDER_APP_LIST_ON_DOCK = '100040|SCENE_MSG_UPDATE_FOLDER_APP_LIST_ON_DOCK',
  // 从文件夹删除快捷方式
  SCENE_MSG_DELETE_SHORTCUT_FROM_FOLDER = '100041|SCENE_MSG_DELETE_SHORTCUT_FROM_FOLDER',
  // 当文件夹里面只有一个元素时更新布局 update layoutInfo when only one item in the folder
  SCENE_MSG_UPDATE_FOLDER_ONLY_ONE_ITEM = '100042|SCENE_MSG_UPDATE_FOLDER_ONLY_ONE_ITEM',
  // 当文件夹里面只有一个元素时更新布局 删除文件夹
  SCENE_MSG_UPDATE_FOLDER_ONLY_ONE_ITEM_DELETE_FOLDER = '100043|SCENE_MSG_UPDATE_FOLDER_ONLY_ONE_ITEM_DELETE_FOLDER',
  // 当文件夹里面只有一个元素时更新布局 其他场景
  SCENE_MSG_UPDATE_FOLDER_ONLY_ONE_ITEM_OTHERS = '100044|SCENE_MSG_UPDATE_FOLDER_ONLY_ONE_ITEM_OTHERS',
  // 拖拽应用离开文件夹
  SCENE_MSG_DRAG_APP_LEAVE_FOLDER = '100045|SCENE_MSG_DRAG_APP_LEAVE_FOLDER',
  // 文件夹内多选
  SCENE_MSG_FOLDER_MULTI_SELECT_LISTENER = '100046|SCENE_MSG_FOLDER_MULTI_SELECT_LISTENER',
  // 文件夹内元素更新
  SCENE_MSG_FOLDER_ITEM_UPDATE_EVENT = '100047|SCENE_MSG_FOLDER_ITEM_UPDATE_EVENT',
  // 更新新安装的应用
  SCENE_MSG_UPDATE_NEW_INSTALLED_APP = '100048|SCENE_MSG_UPDATE_NEW_INSTALLED_APP',
  // 文件夹大小转换
  SCENE_MSG_FOLDER_CONVERT_ANIMATION = '100049|SCENE_MSG_FOLDER_CONVERT_ANIMATION',
  // 恢复文件夹元素
  SCENE_MSG_RECOVER_FOLDER_ITEMS = '100050|SCENE_MSG_RECOVER_FOLDER_ITEMS',
  // 堆叠卡片移除事件结束
  SCENE_MSG_FORM_STACK_DROP_ITEM_ANIMATION_END = '100051|SCENE_MSG_FORM_STACK_DROP_ITEM_ANIMATION_END',
  // 堆叠卡片删除 无动画,不合法
  SCENE_MSG_FORM_STACK_DELETE_CARDS_WITH_NO_ANIMATE_INVALID = '100052|SCENE_MSG_FORM_STACK_DELETE_CARDS_WITH_NO_ANIMATE_INVALID',
  // 堆叠卡片遮罩截图失败
  SCENE_MSG_FORM_STACK_COVER_SNAPSHOT_ERROR = '100053|SCENE_MSG_FORM_STACK_COVER_SNAPSHOT_ERROR',
  // 堆叠卡片遮罩截图
  SCENE_MSG_FORM_STACK_COVER_SNAPSHOT = '100054|SCENE_MSG_FORM_STACK_COVER_SNAPSHOT',
  // 堆叠卡片预加载
  SCENE_MSG_FORM_STACK_PRELOAD_CARD = '100055|SCENE_MSG_FORM_STACK_PRELOAD_CARD',
  // 堆叠卡片拖拽离开堆叠
  SCENE_MSG_FORM_STACK_DRAG_LEAVE_STACK = '100056|SCENE_MSG_FORM_STACK_DRAG_LEAVE_STACK',
  // 演示版本锁定布局拖动
  SCENE_MSG_DISPLAY_LAYOUT_DROP_LOCKED = '100057|SCENE_MSG_DROP_WHEN_LAYOUT_LOCKED',
  // 拖拽结束
  SCENE_MSG_ON_DRAG_DROP_FINAL = '100058|SCENE_MSG_ON_DRAG_DROP_FINAL',
  // 拖拽结束，先执行文件夹消失动效
  SCENE_MSG_ON_DRAG_DROP_FINAL_FOLDER_DISAPPEAR = '100059|SCENE_MSG_ON_DRAG_DROP_FINAL_FOLDER_DISAPPEAR',
  // 拖拽结束，PC中轴场景
  SCENE_MSG_ON_DRAG_DROP_FINAL_CREASE_REGION = '100060|SCENE_MSG_ON_DRAG_DROP_FINAL_CREASE_REGION',
  // 拖拽结束删除空白页,edit mode top bar
  SCENE_MSG_DELETE_BLANK_PAGE_AFTER_DRAGGING_EDIT_MODE_TOP_BAR = '100061|SCENE_MSG_DELETE_BLANK_PAGE_AFTER_DRAGGING_EDIT_MODE_TOP_BAR',
  // 拖拽结束删除空白页,undoDrag onDrop
  SCENE_MSG_DELETE_BLANK_PAGE_AFTER_DRAGGING_UNDO_DRAG = '100062|SCENE_MSG_DELETE_BLANK_PAGE_AFTER_DRAGGING_UNDO_DRAG',
  // 删除拖拽过程中新建的空白页
  SCENE_MSG_DELETE_BLANK_PAGE_ADD_BY_DRAGGING = '100063|SCENE_MSG_DELETE_BLANK_PAGE_ADD_BY_DRAGGING',
  // 删除拖拽过程中新建的空白页,演示版本锁定布局场景
  SCENE_MSG_DELETE_BLANK_PAGE_ADD_BY_DRAGGING_LOCKED_LAYOUT = '100064|SCENE_MSG_DELETE_BLANK_PAGE_ADD_BY_DRAGGING_LOCKED_LAYOUT',
  // 卡片落位动效结束
  SCENE_MSG_FORM_ITEM_DROP_EVENT_FINISHED = '100065|SCENE_MSG_FORM_ITEM_DROP_EVENT_FINISHED',
  // 卡片落位动效结束 beta
  SCENE_MSG_FORM_ITEM_DROP_EVENT_FINISHED_BETA = '100066|SCENE_MSG_FORM_ITEM_DROP_EVENT_FINISHED_BETA',
  // 卡片落位动效结束 alpha
  SCENE_MSG_FORM_ITEM_DROP_EVENT_FINISHED_ALPHA = '100067|SCENE_MSG_FORM_ITEM_DROP_EVENT_FINISHED_ALPHA',
  // 检查更新配置
  SCENE_MSG_CHECK_AND_UPDATE_CONFIG = '100068|SCENE_MSG_CHECK_AND_UPDATE_CONFIG',

  SCENE_MSG_DELETE_ITEMS_FROM_DESKTOP_DROP_FROM_FILE_FOLDER = '100069|SCENE_MSG_DELETE_ITEMS_FROM_DESKTOP_DROP_FROM_FILE_FOLDER',
  // 拖拽元素在大文件夹Grid内落位时处理函数
  SCENE_MSG_DELETE_ITEMS_FROM_DESKTOP_DROP_FOLDER = '100070|SCENE_MSG_DELETE_ITEMS_FROM_DESKTOP_DROP_FOLDER',
  // 添加元素，拖拽元素从文件夹到桌面
  SCENE_MSG_ADD_ITEMS_TO_DESKTOP_DRAG_ITEMS_FROM_FOLDER_TO_DESKTOP = '100071|SCENE_MSG_ADD_ITEMS_TO_DESKTOP_DRAG_ITEMS_FROM_FOLDER_TO_DESKTOP',
  // 添加元素，拖拽元素从文件夹到桌面,移动子元素
  SCENE_MSG_ADD_ITEMS_TO_DESKTOP_DRAG_ITEMS_FROM_FOLDER_TO_DESKTOP_MOVE_SUB_ITEM = '100072|SCENE_MSG_ADD_ITEMS_TO_DESKTOP_DRAG_ITEMS_FROM_FOLDER_TO_DESKTOP_MOVE_SUB_ITEM',
  // 解散分区文件夹（在文管中把映射的文件夹删除了）
  SCENE_MSG_REMOVE_REGION_FOLDER_AFTER_FILE_FOLDER_DELETION = '100073|SCENE_MSG_REMOVE_REGION_FOLDER_AFTER_FILE_FOLDER_DELETION',
  // 解散分区文件夹
  SCENE_MSG_REMOVE_REGION_FOLDER_INNER = '100074|SCENE_MSG_REMOVE_REGION_FOLDER_INNER',
  // 创建多个分区文件夹
  SCENE_MSG_CREATE_REGION_FOLDERS_INNER = '100075|SCENE_MSG_CREATE_REGION_FOLDERS_INNER',
  // REGION_FOLDER 放入已有收纳夹中的item数据更新
  SCENE_MSG_REGION_FOLDER_UPDATE_CLEAN_UP_DATA = '100076|SCENE_MSG_REGION_FOLDER_UPDATE_CLEAN_UP_DATA',
  // REGION_FOLDER 一键撤销
  SCENE_MSG_ROLLBACK_REGION_FOLDER = '100077|SCENE_MSG_ROLLBACK_REGION_FOLDER',
  // 更新文件夹尺寸
  SCENE_MSG_UPDATE_FOLDER_SIZE = '100078|SCENE_MSG_UPDATE_FOLDER_SIZE',
  // 应用安装后更新数据库卡片信息
  SCENE_MSG_SMART_DOCK_UPDATE_FORM_AFTER_APP_INSTALL = '100079|SCENE_MSG_SMART_DOCK_UPDATE_FORM_AFTER_APP_INSTALL',
  // 取消克隆场景桌面已占位图标
  SCENE_MSG_CANCEL_RESTORE_LAUNCHER_APP_IN_DESKTOP = '100080|SCENE_MSG_CANCEL_RESTORE_LAUNCHER_APP_IN_DESKTOP',
  // 屏幕属性变化处理：无动效旋转场景
  SCENE_MSG_SCREEN_CHANGE_ROTATION_NO_ANIM = '100081|SCENE_MSG_SCREEN_CHANGE_ROTATION_NO_ANIM',
  // 屏幕属性变化处理：动效旋转场景
  SCENE_MSG_SCREEN_CHANGE_ROTATION_ANIM = '100082|SCENE_MSG_SCREEN_CHANGE_ROTATION_ANIM',
  // 缓存同步数据库，删除空白页
  SCENE_MSG_CACHE_TO_RDB_EVENT_DELETE_BLANK_PAGE = '100083|SCENE_MSG_CACHE_TO_RDB_EVENT_DELETE_BLANK_PAGE',
  // 检查堆叠是否合法，并清除脏数据 checkAndDealDirtyStack
  SCENE_MSG_CHECK_AND_DEAL_DIRTY_FORM_STACK = '100084|SCENE_MSG_CHECK_AND_DEAL_DIRTY_FORM_STACK',
  SCENE_MSG_DELETE_PAGE = '100085|SCENE_MSG_DELETE_PAGE',
  SCENE_MSG_DRAG_PAGE = '100086|SCENE_MSG_DRAG_PAGE',
  SCENE_MSG_FOLDER_MODE_UPDATE_FOLDER_SIZE = '100087|SCENE_MSG_FOLDER_MODE_UPDATE_FOLDER_SIZE',
  SCENE_MSG_FORM_COMPONENT_ERROR = '100088|SCENE_MSG_FORM_COMPONENT_ERROR',
  SCENE_MSG_UI_EXTENSION_ERROR = '100089|SCENE_MSG_UI_EXTENSION_ERROR',
  SCENE_MSG_UPDATE_FORM_SIZE_AND_POSITION = '100090|SCENE_MSG_UPDATE_FORM_SIZE_AND_POSITION',
  SCENE_MSG_FOLDER_IMAGE_ABOUT_TO_APPEAR = '100091|SCENE_MSG_FOLDER_IMAGE_ABOUT_TO_APPEAR',
  // 从桌面移动应用到文件夹，从桌面缓存中删除
  SCENE_MSG_MOVE_APP_FROM_DESKTOP_TO_FOLDER_DELETE_APP = '100092|SCENE_MSG_MOVE_APP_FROM_DESKTOP_TO_FOLDER_DELETE_APP',
  // 与目标元素合成小文件夹，从桌面缓存中删除
  SCENE_MSG_CREATE_NEW_FOLDER_DELETE_APP = '100093|SCENE_MSG_CREATE_NEW_FOLDER_DELETE_APP',
  // 拖拽新建文件夹，从桌面缓存中删除
  SCENE_MSG_CREATE_NEW_FOLDER_BY_DRAG_DELETE_APP = '100094|SCENE_MSG_CREATE_NEW_FOLDER_BY_DRAG_DELETE_APP',
  // BMS比对
  SCENE_MSG_UPDATE_BMS_CHANGED_APP_DELIVER = '100095|SCENE_MSG_UPDATE_BMS_CHANGED_APP_DELIVER',
  // 企业应用安装状态改变事件
  SCENE_MSG_EVENT_AG_INSTALL_STATUS_CHANGE = '100096|SCENE_MSG_EVENT_AG_INSTALL_STATUS_CHANGE',
  // 合并或加入文件夹
  SCENE_MSG_CREATE_OR_ADD_TO_FOLDER = '100097|SCENE_MSG_CREATE_OR_ADD_TO_FOLDER',
  SCENE_MSG_CREATE_FORM_STACK_WITHOUT_ANIMATION = '100098|SCENE_MSG_CREATE_FORM_STACK_WITHOUT_ANIMATION',
  SCENE_MSG_FORM_STACK_SNAP_IMAGE = '100099|SCENE_MSG_FORM_STACK_SNAP_IMAGE',
  SCENE_MSG_DELETE_CARDS_FROM_FORM_STACK = '100100|SCENE_MSG_DELETE_CARDS_FROM_FORM_STACK',
  SCENE_MSG_DRAG_CARD_BACK_TO_FORM_STACK = '100101|SCENE_MSG_DRAG_CARD_BACK_TO_FORM_STACK',
  SCENE_MSG_PRELOAD_CARD_IN_FORMS_TACK = '100102|SCENE_MSG_PRELOAD_CARD_IN_FORMS_TACK',
  // 初始化Gird布局结束事件
  SCENE_MSG_LAYOUT_INIT_FINISHED = '100103|SCENE_MSG_LAYOUT_INIT_FINISHED',
  SCENE_MSG_DEFAULT_REFRESH = '100200|SCENE_MSG_DEFAULT_REFRESH',
  SCENE_MSG_DEFAULT_INIT_GRID_LIST = '100201|SCENE_MSG_DEFAULT_INIT_GRID_LIST',
  SCENE_MSG_STARTUP_ABNORMAL = '1000202|SCENE_MSG_STARTUP_ABNORMAL',
  SCENE_MSG_LAYOUT_INIT_ABNORMAL = '1000203|SCENE_MSG_LAYOUT_INIT_ABNORMAL',
  SCENE_MSG_PAGE_INDEX_CHANGED = '1000204|SCENE_MSG_PAGE_INDEX_CHANGED',

  // 200000 - 299999 数据库操作场景
  // 按应用插入角标信息
  RDB_INSERT_BADGE_BY_BUNDLE = '200001|RDB_INSERT_BADGE_BY_BUNDLE',
  //  新增文件夹
  RDB_INSERT_FOLDER_LAYOUT = '200002|RDB_INSERT_FOLDER_LAYOUT',
  RDB_INSERT_FOLDER_LAYOUT_INFO = '200003|RDB_INSERT_FOLDER_LAYOUT_INFO',
  RDB_INSERT_FORM_STACK_LAYOUT = '200004|RDB_INSERT_FORM_STACK_LAYOUT',
  RDB_INSERT_ITEM_WITH_OUT_LAYOUT_INFO = '200005|RDB_INSERT_ITEM_WITH_OUT_LAYOUT_INFO',
  RDB_UPDATE_FORM_INFO_BY_POSITION = '200007|RDB_UPDATE_FORM_INFO_BY_POSITION',
  RDB_UPDATE_INTELLIGENT_CARD_LIST = '200008|RDB_UPDATE_INTELLIGENT_CARD_LIST',
  RDB_UPDATE_REGION_FOLDER_INFO = '200009|RDB_UPDATE_REGION_FOLDER_INFO',
  RDB_UPDATE_SUB_ITEMS_INFO = '200010|RDB_UPDATE_SUB_ITEMS_INFO',
  RDB_UPDATE_SWIPER_FORM_INFO = '200011|RDB_UPDATE_SWIPER_FORM_INFO',
  RDB_INSERT_APP_CENTER = '200012|RDB_INSERT_APP_CENTER',
  RDB_INSERT_GRID_LAYOUT_INFO = '200013|RDB_INSERT_GRID_LAYOUT_INFO',
  RDB_BATCH_INSERT_OR_UPDATE_APP_CAT_INFO = '200014|RDB_BATCH_INSERT_OR_UPDATE_APP_CAT_INFO',
  RDB_INSERT_INTO_SMART_DOCK = '200015|RDB_INSERT_INTO_SMART_DOCK',
  RDB_INSERT_INTO_RECENT_DOCK = '200016|RDB_INSERT_INTO_RECENT_DOCK',
  RDB_INSERT_INTO_RECENT_DOCK_INFO = '200017|RDB_INSERT_INTO_RECENT_DOCK_INFO',
  RDB_BATCH_INSERT_BADGE = '200018|RDB_BATCH_INSERT_BADGE',
  RDB_INSERT_INTELLIGENT_DISCOVERY_INFO = '200019|RDB_INSERT_INTELLIGENT_DISCOVERY_INFO',
  RDB_INSERT_OUTER_APP_CATEGORIZE_DATA = '200020|RDB_INSERT_OUTER_APP_CATEGORIZE_DATA',
  RDB_UPDATE_PAGE_INDEX_TYPE_INFO_OF_DB = '200021|RDB_UPDATE_PAGE_INDEX_TYPE_INFO_OF_DB',
  RDB_UPDATE_NEW_INSTALLED_GRID_INFO = '200022|RDB_UPDATE_NEW_INSTALLED_GRID_INFO',
  RDB_UPDATE_CORRECT_SHORTCUT_ITEM_INFO = '200023|RDB_UPDATE_CORRECT_SHORTCUT_ITEM_INFO',
  RDB_UPDATE_APP_ITEM_INTENT_BY_INFO_ID = '200024|RDB_UPDATE_APP_ITEM_INTENT_BY_INFO_ID',
  RDB_UPDATE_APP_NAME_BY_ABILITY_INFO_AND_TYPE = '200025|RDB_UPDATE_APP_NAME_BY_ABILITY_INFO_AND_TYPE',
  RDB_UPDATE_BADGE_DISPLAY_BY_BUNDLE = '200026|RDB_UPDATE_BADGE_DISPLAY_BY_BUNDLE',
  RDB_UPDATE_BADGE_NUM_BY_BUNDLE = '200027|RDB_UPDATE_BADGE_NUM_BY_BUNDLE',
  RDB_UPDATE_CARD_ID_OF_FORM_STACK = '200028|RDB_UPDATE_CARD_ID_OF_FORM_STACK',
  RDB_UPDATE_CONTACT_SHORTCUT_ITEM_INFO = '200029|RDB_UPDATE_CONTACT_SHORTCUT_ITEM_INFO',
  RDB_UPDATE_EXTEND_BY_CARD_ID = '200030|RDB_UPDATE_EXTEND_BY_CARD_ID',
  RDB_UPDATE_FIXED_TYPE_BY_BUNDLE = '200031|RDB_UPDATE_FIXED_TYPE_BY_BUNDLE',
  RDB_UPDATE_FOLDER_INTENT_BY_INFO_ID = '200032|RDB_UPDATE_FOLDER_INTENT_BY_INFO_ID',
  RDB_UPDATE_FORM_CONFIG_INFO = '200033|RDB_UPDATE_FORM_CONFIG_INFO',
  RDB_UPDATE_FORM_INFO_BY_ID = '200034|RDB_UPDATE_FORM_INFO_BY_ID',
  RDB_UPDATE_GRID_INFO = '200035|RDB_UPDATE_GRID_INFO',
  RDB_UPDATE_GRID_INFO_BY_ID = '200036|RDB_UPDATE_GRID_INFO_BY_ID',
  RDB_UPDATE_INTEND_INFO_BY_INFO_ID = '200037|RDB_UPDATE_INTEND_INFO_BY_INFO_ID',
  RDB_UPDATE_SHORTCUT_ITEM_INFO = '200038|RDB_UPDATE_SHORTCUT_ITEM_INFO',
  // 空白页检查纠正
  RDB_UPDATE_BLANK_PAGE_CHECK_CORRECTOR = '200039|RDB_UPDATE_BLANK_PAGE_CHECK_CORRECTOR',
  // 堆叠卡片脏数据处理
  RDB_DIRTY_FORM_STACK_CORRECTOR = '200040|RDB_DIRTY_FORM_STACK_CORRECTOR',
  RDB_UPDATE_BATCH_GRID_LAYOUT_WITH_MAP_REPLACE_GROUP = '200041|RDB_UPDATE_BATCH_GRID_LAYOUT_WITH_MAP_REPLACE_GROUP',
  RDB_BATCH_UPDATE_SHORTCUT_ITEM_LIMIT_INFO = '200042|RDB_BATCH_UPDATE_SHORTCUT_ITEM_LIMIT_INFO',
  RDB_UPDATE_GRID_LAYOUT_POSITION_BATCH = '200043|RDB_UPDATE_GRID_LAYOUT_POSITION_BATCH',
  RDB_UPDATE_GRID_LAYOUT_INFO_POSITION_BY_PAGE = '200044|RDB_UPDATE_GRID_LAYOUT_INFO_POSITION_BY_PAGE',
  RDB_UPDATE_DOWNLOAD_INFO = '200045|RDB_UPDATE_DOWNLOAD_INFO',
  RDB_UPDATE_RELATION_FORM_INFO_OF_DB = '200046|RDB_UPDATE_RELATION_FORM_INFO_OF_DB',
  RDB_DELETE_ALL_GRID_INFO_DATA = '200047|RDB_DELETE_ALL_GRID_INFO_DATA',
  RDB_DELETE_ALL_RECENT_DOCK_DATA = '200048|RDB_DELETE_ALL_RECENT_DOCK_DATA',
  RDB_DELETE_APP_CENTER_ITEM = '200049|RDB_DELETE_APP_CENTER_ITEM',
  RDB_DELETE_BADGE_BY_BUNDLE = '200050|RDB_DELETE_BADGE_BY_BUNDLE',
  RDB_DELETE_FEED_HEAD_PIC_BY_MODULE_NAME = '200052|RDB_DELETE_FEED_HEAD_PIC_BY_MODULE_NAME',
  RDB_DELETE_FILE_FOLDER_ITEM = '200053|RDB_DELETE_FILE_FOLDER_ITEM',
  RDB_DELETE_FORM_INFO_BY_ID = '200054|RDB_DELETE_FORM_INFO_BY_ID',
  RDB_DELETE_FORM_INFO_BY_POSITION = '200055|RDB_DELETE_FORM_INFO_BY_POSITION',
  RDB_DELETE_FORM_IN_FORM_STACK_BY_NAME_AND_CONTAINER = '200056|RDB_DELETE_FORM_IN_FORM_STACK_BY_NAME_AND_CONTAINER',
  RDB_DELETE_GRID_LAYOUT_BY_CONDITION = '200057|RDB_DELETE_GRID_LAYOUT_BY_CONDITION',
  RDB_DELETE_INFO_BY_BUNDLE = '200058|RDB_DELETE_INFO_BY_BUNDLE',
  RDB_DELETE_INTELLIGENT_COMMON_DATA = '200059|RDB_DELETE_INTELLIGENT_COMMON_DATA',
  RDB_DELETE_ITEM_BY_INFO_ID = '200060|RDB_DELETE_ITEM_BY_INFO_ID',
  RDB_DELETE_LAYOUT_INFO_BY_ID = '200061|RDB_DELETE_LAYOUT_INFO_BY_ID',
  RDB_DELETE_OUTER_INFO_BY_BUNDLE = '200062|RDB_DELETE_OUTER_INFO_BY_BUNDLE',
  RDB_DELETE_RECENT_DOCK_BY_BUNDLE = '200063|RDB_DELETE_RECENT_DOCK_BY_BUNDLE',
  RDB_DELETE_SHORTCUT_ITEM = '200064|RDB_DELETE_SHORTCUT_ITEM',
  RDB_DELETE_SMART_DOCK_BY_BUNDLE_AND_APP_INDEX = '200065|RDB_DELETE_SMART_DOCK_BY_BUNDLE_AND_APP_INDEX',
  RDB_DELETE_SMART_DOCK_ITEM = '200066|RDB_DELETE_SMART_DOCK_ITEM',
  RDB_DROP_FORM_TABLE = '200067|RDB_DROP_FORM_TABLE',
  RDB_DELETE_RELATION_FORM_INFO_OF_DB = '200068|RDB_DELETE_RELATION_FORM_INFO_OF_DB',
  RDB_DELETE_ITEMS_BY_INFO_ID_AND_CONTAINER = '200069|RDB_DELETE_ITEMS_BY_INFO_ID_AND_CONTAINER',
  RDB_UPDATE_APP_CENTER_SYS = '200070|RDB_UPDATE_APP_CENTER_SYS',
  RDB_DEFAULT_QUERY = '200071|RDB_DEFAULT_QUERY',
  // 更新元素信息到数据库,不区分桌面或者dock
  RDB_UPDATE_ALL_INFO_POSITION = '200072|RDB_UPDATE_ALL_INFO_POSITION',
  RDB_UPDATE_INFO_POSITION = '200073|RDB_UPDATE_INFO_POSITION',
  RDB_UPDATE_APP_CENTER_ITEM_POSITIONS = '200070|RDB_UPDATE_APP_CENTER_ITEM_POSITIONS',
  RDB_DEFAULT_INSERT = '200080|RDB_DEFAULT_INSERT',
  RDB_DEFAULT_UPDATE = '200081|RDB_DEFAULT_UPDATE',
  RDB_DEFAULT_BATCH_INSERT = '200082|RDB_DEFAULT_BATCH_INSERT',
  RDB_DEFAULT_DELETE = '200083|RDB_DEFAULT_DELETE',
  RDN_DEFAULT_QUERY = '200084|RDB_DEFAULT_QUERY',
  RDN_DEFAULT_INIT = '200085|RDB_DEFAULT_INIT',
  RDB_INSERT_FORM_INFO_BY_POSITION = '200086|RDB_INSERT_FORM_INFO_BY_POSITION',
  RDB_INSERT_FORM_INFO_BY_ID = '200087|RDB_INSERT_FORM_INFO_BY_ID',
  FILTER_DB_LIST_BY_INSTALLED = '200088|FILTER_DB_LIST_BY_INSTALLED',
  DELETE_ABNORMAL_DESKTOP_DATA = '200089|DELETE_ABNORMAL_DESKTOP_DATA',
  DELETE_GRID_LAYOUT_BY_KEYNAME = '200090|DELETE_GRID_LAYOUT_BY_KEYNAME',
  DELETE_APP_ITEM_CALLBACK =  '200091|DELETE_APP_ITEM_CALLBACK',
  DELETE_APP_CENTER_ITEM = '200092|DELETE_APP_CENTER_ITEM',
  DELETE_QUERY_SMART_DOCK_FOLDER = '200093|DELETE_QUERY_SMART_DOCK_FOLDER',
  DELETE_QUERY_SMART_DOCK = '200094|DELETE_QUERY_SMART_DOCK',
  MINOR_UPDATE = '200095|MINOR_UPDATE',
  INSERT_DRAWER_MODE_APP_INFO = '200096|INSERT_DRAWER_MODE_APP_INFO',
  MASS_UPDATE = '200097|MASS_UPDATE',
  MASS_BATCH_INSERT = '200098|MASS_BATCH_INSERT',

  // 300000 - 399999 缓存操作场景
  CACHE_UPDATE_DEFAULT = '300001|CACHE_UPDATE_DEFAULT',
  CACHE_DELETE_DEFAULT = '300002|CACHE_UPDATE_DEFAULT',
  CACHE_UPDATE_LAYOUT_LIST_CACHE_DEFAULT = '300003|CACHE_UPDATE_LAYOUT_LIST_CACHE_DEFAULT',
  CACHE_UPDATE_LAYOUT_LIST_CACHE_AND_PREBUILD = '300004|CACHE_UPDATE_LAYOUT_LIST_CACHE_AND_PREBUILD',

  CACHE_UNINSTALL_APP_DELETE_OUTER_SHORTCUT = '300005|CACHE_UNINSTALL_APP_DELETE_OUTER_SHORTCUT',
  CACHE_DELETE_OUTER_SHORTCUT = '300006|CACHE_DELETE_OUTER_SHORTCUT',

  // 未定义场景
  SCENE_MSG_UNDEFINED = '999999|SCENE_MSG_UNDEFINED',
}


export enum RDBErrorCode {
  EMPTY_PARAM = 10001,
  DISABLE_INSERT = 10002,
  DUPLICATE_POSITION = 10003,
}

export enum IconDataDebugParam {
  ICON_OPACITY = 'iconOpacity',
  CONTAINER_OPACITY = 'containerOpacity',
  ICON_ID = 'iconId',
}