/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2024-2025. All rights reserved.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
export class AppCenterSceneConstants {
  public static readonly ENTER_MISSION_CENTER = 0;
  public static readonly EXIT_MISSION_CENTER = 1;
  public static readonly ENTER_TFS_WINDOW = 2;
  public static readonly EXIT_TFU_WINDOW = 3;
  public static readonly ENTER_WINDOW_FULL_SCREEN = 4;
  public static readonly EXIT_WINDOW_FULL_SCREEN = 5;
  public static readonly ENTER_MAX_WINDOW = 6;
  public static readonly EXIT_MAX_WINDOW = 7;
  public static readonly ENTER_SPLIT_WINDOW = 8;
  public static readonly EXIT_SPLIT_WINDOW = 9;
  public static readonly ENTER_APP_CENTER = 10;
  public static readonly EXIT_APP_CENTER = 11;
  public static readonly APPEAR_MISSION_CENTER = 12;
  public static readonly ENTER_WIND_CLEAR = 13;
  public static readonly ENTER_WIND_RECOVER = 14;
  public static readonly OTHERS = 15;
  public static readonly APP_CENTER_BLUR_DURATION: number = 400;
}