/*
 * Copyright (c) 2026 Huawei Device Co., Ltd. All rights reserved.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * 全局 AppStorage Key
 */
export enum AppStorageKey {
  // 深浅色模式
  COLOR_MODE = 'colorMode',
  // 避让导航栏高度
  NAVIGATION_BAR_HEIGHT = 'navigationBarHeight',
  // 是否保持深色模式样式
  IS_SHOW_AS_DARK_MODE = 'isShowAsDarkMode',
}